import { Role } from '@prisma/client';

export const PERMISSIONS = {
  DESTINATION_CREATE: [Role.STUDENT, Role.LEADER, Role.LECTURER, Role.SUPER_ADMIN],
  ROUTE_CREATE: [Role.STUDENT, Role.LEADER, Role.LECTURER, Role.SUPER_ADMIN],
  TOUR_CREATE: [Role.STUDENT, Role.LEADER, Role.LECTURER, Role.SUPER_ADMIN],
  PROVIDER_MANAGE: [Role.LECTURER, Role.SUPER_ADMIN],
  APPROVAL_REVIEW: [Role.LEADER, Role.LECTURER, Role.SUPER_ADMIN],
  ADMIN_MANAGE: [Role.SUPER_ADMIN],
} as const;
